//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterStare
    {
        public int Sid { get; set; }
        public decimal Price { get; set; }
        public int Centerclass { get; set; }
        public int Service { get; set; }
        public int Env { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Uid { get; set; }
        public int Mid { get; set; }
        public int Satate { get; set; }
    }
}
