//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.ClassReport = new HashSet<ClassReport>();
            this.ClassTeacher = new HashSet<ClassTeacher>();
            this.ClassTopic = new HashSet<ClassTopic>();
            this.InterestedClass = new HashSet<InterestedClass>();
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int YogaTypeID { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public string Banner { get; set; }
        public string Start { get; set; }
        public int Duration { get; set; }
        public int DurationUnit { get; set; }
        public int AreaID { get; set; }
        public string Address { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public bool IsItem { get; set; }
        public int ItemClassID { get; set; }
        public int Max { get; set; }
        public int ClassType { get; set; }
        public int ClassStatus { get; set; }
        public string NoPassMsg { get; set; }
        public int UserId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Name { get; set; }
        public string TopicIds { get; set; }
        public string Tags { get; set; }
        public Nullable<int> iReadNums { get; set; }
        public System.DateTime CloseTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string MessageDes { get; set; }
        public string CenterID { get; set; }
        public Nullable<int> FieldID { get; set; }
        public Nullable<int> iShareNums { get; set; }
    
        public virtual ICollection<ClassReport> ClassReport { get; set; }
        public virtual ICollection<ClassTeacher> ClassTeacher { get; set; }
        public virtual ICollection<ClassTopic> ClassTopic { get; set; }
        public virtual ICollection<InterestedClass> InterestedClass { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual YogaUser User { get; set; }
    }
}
