//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTeacher
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string YogaSystem { get; set; }
        public string Info { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Class_Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string Avatar { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
