//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public int Duration { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Level { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CenterID { get; set; }
        public string Address { get; set; }
        public int UserID { get; set; }
        public int YID { get; set; }
        public string Mark { get; set; }
        public string Mark2 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
