//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTopic
    {
        public int Id { get; set; }
        public int ClassID { get; set; }
        public int TopicID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
