//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassReport
    {
        public ClassReport()
        {
            this.ClassFile = new HashSet<ClassFile>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int UserId { get; set; }
        public int ClassId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<ClassFile> ClassFile { get; set; }
    }
}
