//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int Followid { get; set; }
        public int Uid { get; set; }
        public int QuiltUid { get; set; }
        public System.DateTime FollowDate { get; set; }
        public Nullable<int> QuiltCenterID { get; set; }
        public Nullable<bool> isfollow { get; set; }
        public Nullable<int> iType { get; set; }
        public Nullable<int> loginType { get; set; }
    
        public virtual YogaUser YogaUser { get; set; }
        public virtual YogaUser YogaUser1 { get; set; }
    }
}
