//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelOrder
    {
        public int ID { get; set; }
        public string LevelOrderID { get; set; }
        public int UID { get; set; }
        public string Name { get; set; }
        public string OrderType { get; set; }
        public string OrderState { get; set; }
        public string OrderScore { get; set; }
        public int OrderDel { get; set; }
        public string OriginalLevel { get; set; }
        public string TargetLevel { get; set; }
        public Nullable<int> ManageID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Reason { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
    }
}
