//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Phone { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public string PayAccount { get; set; }
        public string Payment { get; set; }
        public bool IsPaid { get; set; }
        public int UserId { get; set; }
        public int ClassId { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string PayNO { get; set; }
        public string PayDomain { get; set; }
        public int Id { get; set; }
        public string openid { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
