//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Space
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int PersonNum { get; set; }
        public string Content { get; set; }
        public bool IsDefault { get; set; }
        public string Point { get; set; }
        public int OwnerID { get; set; }
        public System.DateTime OpenTime { get; set; }
        public System.DateTime CloseTime { get; set; }
        public decimal PriceOfDay { get; set; }
        public decimal PriceOfHour { get; set; }
        public decimal PriceOfMonth { get; set; }
        public bool IsRenting { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
