//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBanner
    {
        public int ID { get; set; }
        public string spic { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string sUrl { get; set; }
        public Nullable<int> iType { get; set; }
    }
}
