//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInstationInfo
    {
        public int ID { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string sContent { get; set; }
        public Nullable<int> iType { get; set; }
        public string CreateUser { get; set; }
        public Nullable<bool> ifDel { get; set; }
        public Nullable<int> loginType { get; set; }
    }
}
