//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLearing
    {
        public int ID { get; set; }
        public string Uid { get; set; }
        public string sPic { get; set; }
        public string sTitle { get; set; }
        public Nullable<int> iReadNums { get; set; }
        public Nullable<int> iWritelogNums { get; set; }
        public Nullable<int> iZanNums { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> iType { get; set; }
        public string sContent { get; set; }
        public Nullable<bool> ifexamine { get; set; }
        public Nullable<int> UrlType { get; set; }
    }
}
