//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMessage
    {
        public int ID { get; set; }
        public Nullable<int> ToUid { get; set; }
        public string sContent { get; set; }
        public Nullable<int> FromUid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> iZan { get; set; }
        public Nullable<int> iAudio { get; set; }
        public Nullable<int> ToType { get; set; }
        public Nullable<int> FormType { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string photo { get; set; }
        public Nullable<int> Toid { get; set; }
        public Nullable<int> loginType { get; set; }
    }
}
