//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogaUser
    {
        public YogaUser()
        {
            this.Follow = new HashSet<Follow>();
            this.Follow1 = new HashSet<Follow>();
            this.YogisModels = new HashSet<YogisModels>();
            this.Classes = new HashSet<Class>();
        }
    
        public int Uid { get; set; }
        public string UEmail { get; set; }
        public string Uphone { get; set; }
        public string Pwd { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> UStatus { get; set; }
        public Nullable<bool> IsAssessor { get; set; }
        public Nullable<bool> IsWebworkers { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string LastIP { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> LoginType { get; set; }
        public string SinaAuthCode { get; set; }
        public string SinaBack { get; set; }
        public string QQAuthCode { get; set; }
        public string QQBack { get; set; }
        public string WechatAuthCode { get; set; }
        public string WechatBack { get; set; }
        public string ValCode { get; set; }
        public Nullable<System.DateTime> ValExpire { get; set; }
        public Nullable<int> delState { get; set; }
        public string salt { get; set; }
        public Nullable<int> InputType { get; set; }
        public string objectId { get; set; }
    
        public virtual ICollection<Follow> Follow { get; set; }
        public virtual ICollection<Follow> Follow1 { get; set; }
        public virtual ICollection<YogisModels> YogisModels { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}
