//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogaArticle
    {
        public int ID { get; set; }
        public int ClassID { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleCon { get; set; }
        public int CheckID { get; set; }
        public int IsCheck { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Author { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int IsDelete { get; set; }
        public int IsPicture { get; set; }
        public string PicPath { get; set; }
    }
}
