//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogaUserDetail
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public string RealName_cn { get; set; }
        public Nullable<int> IsRealName_cn { get; set; }
        public string RealName_en { get; set; }
        public Nullable<int> IsRealName_en { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public Nullable<int> IsBirthYear { get; set; }
        public Nullable<int> BirthMonth { get; set; }
        public Nullable<int> IsBirthMonth { get; set; }
        public Nullable<int> BirthDay { get; set; }
        public Nullable<int> IsBirthDay { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> IsNationality { get; set; }
        public string Street { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string MSN { get; set; }
        public Nullable<int> IsMsn { get; set; }
        public string QQ { get; set; }
        public Nullable<int> IsQQ { get; set; }
        public string Postal { get; set; }
        public Nullable<int> IsPostal { get; set; }
        public string Zip { get; set; }
        public Nullable<int> IsZip { get; set; }
        public string Tel { get; set; }
        public Nullable<int> IsTel { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> IsMobile { get; set; }
        public string Profile { get; set; }
        public string Weibo { get; set; }
        public Nullable<int> IsWeibo { get; set; }
        public string PersonalURL { get; set; }
        public Nullable<int> IsPersonalURL { get; set; }
        public Nullable<int> StartYear { get; set; }
        public string IsUserYogaType { get; set; }
        public string IsUserYogaPlace { get; set; }
        public Nullable<bool> IsYogisMap { get; set; }
        public string GudWords { get; set; }
        public string DisplayImg { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Ulevel { get; set; }
        public int Uscore { get; set; }
        public string AlipayUser { get; set; }
        public Nullable<System.DateTime> UpgradeDate { get; set; }
        public string YogaTypeid { get; set; }
        public Nullable<int> iZan { get; set; }
        public string IsUserWeeknumber { get; set; }
        public string sContent { get; set; }
        public string knowledge { get; set; }
        public string Covimg { get; set; }
        public Nullable<int> delState { get; set; }
    }
}
