//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogaMenus
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> state { get; set; }
        public string url { get; set; }
        public Nullable<int> ordervalue { get; set; }
    }
}
