//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogaPicture
    {
        public int Pid { get; set; }
        public Nullable<int> PictureType { get; set; }
        public int Uid { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> EvaluateId { get; set; }
        public Nullable<int> Comid { get; set; }
        public string PictureName { get; set; }
        public string PictureContent { get; set; }
        public string PictureOriginal { get; set; }
        public string PictureLarge { get; set; }
        public string PictureMiddle { get; set; }
        public string PictureSmall { get; set; }
        public string PircureSize { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> NotLikeCount { get; set; }
        public Nullable<int> CommentLimite { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> LastChangeTime { get; set; }
        public Nullable<int> HitNum { get; set; }
        public Nullable<int> iAudio { get; set; }
    }
}
