//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogiProfile
    {
        public int ProfileID { get; set; }
        public int UID { get; set; }
        public string IDType { get; set; }
        public string IDNum { get; set; }
        public string IDPhoto { get; set; }
        public string IDScan { get; set; }
        public string IDScanF { get; set; }
        public string Diploma { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpgradeDate { get; set; }
        public string sMemo { get; set; }
    }
}
