//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IYogaKoo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YogisModels
    {
        public int YID { get; set; }
        public int UID { get; set; }
        public string RealName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Headid { get; set; }
        public string CenterID { get; set; }
        public string YogaTypeid { get; set; }
        public string TeachYogis { get; set; }
        public string EachClassCost { get; set; }
        public string IdType { get; set; }
        public string IdCardNum { get; set; }
        public Nullable<System.DateTime> StartTeachYear { get; set; }
        public string Nationality { get; set; }
        public string Street { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> YogisLevel { get; set; }
        public Nullable<int> YogiStatus { get; set; }
        public Nullable<System.DateTime> BecomeYogisTime { get; set; }
        public Nullable<int> YogisScore { get; set; }
        public string DisplayImg { get; set; }
        public Nullable<bool> IsPayRecord { get; set; }
        public Nullable<int> Profileid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpgradeDate { get; set; }
        public Nullable<bool> IsAcceptAgreement { get; set; }
        public string YogisDepict { get; set; }
        public string GudWords { get; set; }
        public Nullable<int> iRate { get; set; }
        public string CoverImg { get; set; }
        public Nullable<int> delState { get; set; }
        public string Leveldetails { get; set; }
        public Nullable<int> iZan { get; set; }
    
        public virtual YogaUser YogaUser { get; set; }
    }
}
